/*! SafariExtension v4.3.0. Upstream (c) Adguard Software Ltd., GPL-3.0, https://github.com/AdguardTeam/SafariConverterLib/tree/master/Extension */
/*! Generated artifact — do not edit. Edit extension-src/content.js and run scripts/minify-extension-js.sh */
function _defineProperty2(m,g,d){return(g=_toPropertyKey(g))in m?Object.defineProperty(m,g,{value:d,enumerable:!0,configurable:!0,writable:!0}):m[g]=d,m}installWBlockDiagnosticCodes();function installWBlockDiagnosticCodes(){const m=/^\[WBLOCK_[A-Z0-9_]+\]$/;for(const[g,d]of[["error","WBLOCK_UNCLASSIFIED_ERROR"],["warn","WBLOCK_UNCLASSIFIED_WARNING"]]){if(console[g]?.wBlockDiagnosticCodesInstalled===!0)continue;const N=console[g].bind(console),pe=(...j)=>{const q=j[0];typeof q=="string"&&m.test(q.
split(" ",1)[0])?N(...j):typeof q=="string"?N(`[${d}] ${q}`,...j.slice(1)):N(`[${d}]`,...j)};Object.defineProperty(pe,"wBlockDiagnosticCodesInstalled",{value:!0}),console[g]=pe}}function _toPropertyKey(m){var g=_toPrimitive(m,"string");return typeof g=="symbol"?g:g+""}function _toPrimitive(m,g){if(typeof m!="object"||!m)return m;var d=m[Symbol.toPrimitive];if(d!==void 0){var N=d.call(m,g||"default");if(typeof N!="object")return N;throw new TypeError("@@toPrimitive must return a primitive value.")}
return(g==="string"?String:Number)(m)}(function(m){"use strict";function g(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}const d={SELECTOR_LIST:"SelectorList",SELECTOR:"Selector",REGULAR_SELECTOR:"RegularSelector",EXTENDED_SELECTOR:"ExtendedSelector",ABSOLUTE_PSEUDO_CLASS:"AbsolutePseudoClass",RELATIVE_PSEUDO_CLASS:"RelativePseudoClass"};class N{constructor(r){g(this,"children",[]),this.type=r}addChild(r){this.children.push(r)}}class pe extends N{constructor(r){
super(d.REGULAR_SELECTOR),this.value=r}}class j extends N{constructor(r){super(d.RELATIVE_PSEUDO_CLASS),this.name=r}}class q extends N{constructor(r){super(d.ABSOLUTE_PSEUDO_CLASS),g(this,"value",""),this.name=r}}const wt="[",vt="]",Ot="(",yt=")",bt="{",At="}",h={SQUARE:{LEFT:wt,RIGHT:vt},PARENTHESES:{LEFT:Ot,RIGHT:yt},CURLY:{LEFT:bt,RIGHT:At}},R="/",$="\\",U=" ",Q=",",xe=".",Se=";",A=":",B="'",_='"',Ct="^",Lt="$",J="=",ne="	",oe="\r",ie=`
`,le="\f",Pt=[U,ne,oe,ie,le],v="*",Ve="#",Ge=xe,me=U,ae=">",ce="+",ue="~",ge=[me,ae,ce,ue],_t=[wt,vt,Ot,yt,bt,At,R,$,Se,A,Q,B,_,Ct,Lt,v,Ve,Ge,me,ae,ce,ue,ne,oe,ie,le],Ir=[A,Se,B,_,$,U,ne,oe,ie,le],Fe="contains",He="has-text",We="-abp-contains",Nt="matches-css",$t="matches-css-before",It="matches-css-after",kt="matches-attr",Dt="matches-property",Y="xpath",Ye="nth-ancestor",kr=[Fe,He,We],Ke="upward",x="remove",Mt="has",Ut="-abp-has",Xe=[Mt,Ut],ze="is",je="not",Bt=[Fe,He,We,Nt,$t,It,kt,Dt,Y,Ye,Ke],
xt=[...Xe,ze,je],qe=[...Bt,...xt],Dr=[je,ze],Qe=":scope",Vt={AFTER:"after",BACKDROP:"backdrop",BEFORE:"before",CUE:"cue",CUE_REGION:"cue-region",FIRST_LETTER:"first-letter",FIRST_LINE:"first-line",FILE_SELECTION_BUTTON:"file-selector-button",GRAMMAR_ERROR:"grammar-error",MARKER:"marker",PART:"part",PLACEHOLDER:"placeholder",SELECTION:"selection",SLOTTED:"slotted",SPELLING_ERROR:"spelling-error",TARGET_TEXT:"target-text"},Gt="@",Je="content",Z="true",Ft="global",Re="Selector should be defined",P={
NO_STYLE:"No style declaration found",NO_SELECTOR:`${Re} before style declaration in stylesheet`,INVALID_STYLE:"Invalid style declaration",UNCLOSED_STYLE:"Unclosed style declaration",NO_PROPERTY:"Missing style property in declaration",NO_VALUE:"Missing style value in declaration",NO_STYLE_OR_REMOVE:"Style should be declared or :remove() pseudo-class should used",NO_COMMENT:"Comments are not supported"},Ht="At-rules are not supported",K={INVALID_REMOVE:"Invalid :remove() pseudo-class in selector",
NO_TARGET_SELECTOR:`${Re} before :remove() pseudo-class`,MULTIPLE_USAGE:"Pseudo-class :remove() appears more than once in selector",INVALID_POSITION:"Pseudo-class :remove() should be at the end of selector"},Mr="Error while matching element",Wt=50,Ur=/\[-(?:ext)-([a-z-_]+)=(["'])((?:(?=(\\?))\4.)*?)\2\]/g,Br="[-ext-",xr=(e,r,t,s)=>{const n=new RegExp(`([^\\\\]|^)\\\\${t}`,"g"),o=s.replace(n,`$1${t}`);return`:${r}(${o})`},Vr=/\(:scope >/g,Gr="(>",Fr=/(:matches-css)-(before|after)\(/g,Hr=(e,r,t)=>`${r}${h.
PARENTHESES.LEFT}${t}${Q}`,Wr=e=>{const r=e.replace(Ur,xr).replace(Vr,Gr).replace(Fr,Hr);if(r.includes(Br))throw new Error(`Invalid extended-css old syntax selector: '${e}'`);return r},Yr=e=>{const r=e.trim();return Wr(r)},C={MARK:"mark",WORD:"word"},Ze=(e,r)=>{let t="";const s=[];return e.split("").forEach(o=>{if(r.includes(o)){t.length>0&&(s.push({type:C.WORD,value:t}),t=""),s.push({type:C.MARK,value:o});return}t+=o}),t.length>0&&s.push({type:C.WORD,value:t}),s},Kr=e=>{const r=Yr(e);return Ze(
r,_t)},Xr=e=>Ze(e,[..._t,J]),et=e=>{const r=[];e.forEach(s=>r.push(s));const t=[];for(;r.length;){const s=r.pop();if(!s)throw new Error("Unable to make array flat");Array.isArray(s)?s.forEach(n=>r.push(n)):t.push(s)}return t.reverse()},ee=e=>e[0],V=e=>e[e.length-1],Yt=e=>e[e.length-2],Te=(e,r,t)=>{const s=e[r];if(!s)throw new Error(t||`No array item found by index ${r}`);return s},Kt="At least one of Selector node children should be RegularSelector",we=e=>e?.type===d.SELECTOR_LIST,te=e=>e?.type===
d.SELECTOR,y=e=>e?.type===d.REGULAR_SELECTOR,re=e=>e.type===d.EXTENDED_SELECTOR,I=e=>e?.type===d.ABSOLUTE_PSEUDO_CLASS,G=e=>e?.type===d.RELATIVE_PSEUDO_CLASS,F=e=>{if(e===null)throw new Error("Ast node should be defined");if(!I(e)&&!G(e))throw new Error("Only AbsolutePseudoClass or RelativePseudoClass ast node can have a name");if(!e.name)throw new Error("Extended pseudo-class should have a name");return e.name},L=(e,r)=>{if(e===null)throw new Error("Ast node should be defined");if(!y(e)&&!I(e))
throw new Error("Only RegularSelector ot AbsolutePseudoClass ast node can have a value");if(!e.value)throw new Error(r||"Ast RegularSelector ot AbsolutePseudoClass node should have a value");return e.value},Xt=e=>e.filter(y),zr=(e,r)=>{const t=Xt(e),s=ee(t);if(!s)throw new Error(r||Kt);return s},zt=e=>{const r=Xt(e),t=V(r);if(!t)throw new Error(Kt);return t},ve=(e,r)=>{if(e.children.length!==1)throw new Error(r);const t=ee(e.children);if(!t)throw new Error(r);return t},Oe=e=>ve(e,"Extended selec\
tor should be specified"),tt=e=>{if(!G(e))throw new Error("Only RelativePseudoClass node can have relative SelectorList node as child");return ve(e,`Missing arg for :${F(e)}() pseudo-class`)},jr="i",jt={COMMON:[h.PARENTHESES.LEFT,B,_,J,xe,A,U],CONTAINS:[h.PARENTHESES.LEFT,B,_]},rt=e=>qe.includes(e),st=e=>Dr.includes(e),qt=(e,r)=>!e||!r?!1:ge.includes(r)||e===C.WORD||r===v||r===Ve||r===Ge||r===A||r===B||r===_||r===h.SQUARE.LEFT,qr=(e,r,t)=>{const s=V(e.extendedPseudoNamesStack);if(!s)throw new Error(
"Regexp pattern allowed only in arg of extended pseudo-class");if(kr.includes(s))return jt.CONTAINS.includes(r);if(r===R&&s!==Y){const n=t?`in arg part: '${t}'`:"arg";throw new Error(`Invalid regexp pattern for :${s}() pseudo-class ${n}`)}return jt.COMMON.includes(r)},de=(e,r)=>e===h.SQUARE.LEFT&&r!==$,Qr=e=>{var r;if(!e.isAttributeBracketsOpen)return!1;const t=e.attributeBuffer.split(U).join(""),s=Xr(t),n=ee(s),o=n?.type,i=n?.value;if(o===C.MARK&&i!==$)throw new Error(`'[${e.attributeBuffer}]' \
is not a valid attribute due to '${i}' at start of it`);const l=V(s),c=l?.type,a=l?.value;if(a===J)throw new Error(`'[${e.attributeBuffer}]' is not a valid attribute due to '${J}'`);const f=s.findIndex(H=>H.type===C.MARK&&H.value===J),E=(r=Yt(s))===null||r===void 0?void 0:r.value;if(f===-1)return c===C.WORD?!0:E===$&&(a===_||a===B);const M=Te(s,f+1).value;if(!(M===B||M===_)){if(c===C.WORD)return!0;throw new Error(`'[${e.attributeBuffer}]' is not a valid attribute`)}return c===C.WORD&&a?.toLocaleLowerCase()===
jr?E===M:a===M},Qt=e=>e?Pt.includes(e):!1,ye=e=>Bt.includes(e),Jt=e=>xt.includes(e),X=e=>e.pathToBufferNode.length===0?null:V(e.pathToBufferNode)||null,Jr=e=>e.pathToBufferNode.length<2?null:Yt(e.pathToBufferNode)||null,nt=e=>{const r=X(e);if(!r)throw new Error("No bufferNode found");if(!te(r))throw new Error("Unsupported bufferNode type");const t=zt(r.children);return e.pathToBufferNode.push(t),t},S=(e,r)=>{const t=X(e);if(t===null)throw new Error("No bufferNode to update");if(I(t))t.value+=r;else if(y(
t))t.value+=r,e.isAttributeBracketsOpen&&(e.attributeBuffer+=r);else throw new Error(`${t.type} node cannot be updated. Only RegularSelector and AbsolutePseudoClass are supported`)},Zr=e=>{const r=new N(d.SELECTOR_LIST);e.ast=r,e.pathToBufferNode.push(r)},O=function(e,r){let t=arguments.length>2&&arguments[2]!==void 0?arguments[2]:"";const s=X(e);if(s===null)throw new Error("No buffer node");let n;r===d.REGULAR_SELECTOR?n=new pe(t):r===d.ABSOLUTE_PSEUDO_CLASS?n=new q(t):r===d.RELATIVE_PSEUDO_CLASS?
n=new j(t):n=new N(r),s.addChild(n),e.pathToBufferNode.push(n)},be=(e,r)=>{Zr(e),O(e,d.SELECTOR),O(e,d.REGULAR_SELECTOR,r)},Ae=function(e){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"";O(e,d.SELECTOR_LIST),O(e,d.SELECTOR),O(e,d.REGULAR_SELECTOR,r)},D=(e,r)=>{for(let s=e.pathToBufferNode.length-1;s>=0;s-=1){var t;if(((t=e.pathToBufferNode[s])===null||t===void 0?void 0:t.type)===r){e.pathToBufferNode=e.pathToBufferNode.slice(0,s+1);break}}},Zt=e=>{const r=X(e);if(r&&we(r)&&G(Jr(e)))
return r;D(e,d.SELECTOR);const t=X(e);if(!t)throw new Error("No SelectorNode, impossible to continue selector parsing by ExtendedCss");const s=V(t.children),n=s&&re(s)&&e.standardPseudoBracketsStack.length===0,o=n&&ee(s.children);let i=t;if(o){const l=n&&o.name,c=l&&Jt(l),a=l&&ye(l),f=c&&e.extendedPseudoBracketsStack.length>0&&e.extendedPseudoBracketsStack.length===e.extendedPseudoNamesStack.length,E=a&&l===V(e.extendedPseudoNamesStack);(f||E)&&(e.pathToBufferNode.push(s),i=o)}else n?i=t:i=nt(e);
return e.pathToBufferNode.push(i),i},er=(e,r,t,s,n)=>{if(!s)throw new Error(`Invalid colon ':' at the end of selector: '${r}'`);if(rt(s.toLowerCase())){if(Xe.includes(s)&&e.standardPseudoNamesStack.length>0)throw new Error(`Usage of :${s}() pseudo-class is not allowed inside regular pseudo: '${V(e.standardPseudoNamesStack)}'`);D(e,d.SELECTOR),O(e,d.EXTENDED_SELECTOR)}else{if(s.toLowerCase()===x)throw new Error(`${K.INVALID_REMOVE}: '${r}'`);S(e,t),n&&n===h.PARENTHESES.LEFT&&!e.isAttributeBracketsOpen&&
e.standardPseudoNamesStack.push(s)}},es=`html ${v}`,ts=e=>e.children.some(r=>r.children.some(t=>re(t))),rs=e=>e.children.map(t=>{const s=ve(t,"Ast Selector node should have RegularSelector node");return L(s)}).join(`${Q}${U}`),Ce=(e,r)=>(e.children=r,e),ot=e=>{if(e===null)return!1;const r=Oe(e),t=F(r);if(ye(t))return!1;const n=tt(r).children;return st(t)&&n.every(i=>{try{const l=ve(i,"Selector node should have RegularSelector");return y(l)}catch{return!1}})?!0:n.some(o=>o.children.some(i=>re(i)?
ot(i):!1))},ss=(e,r)=>{if(!e)return null;const t=Oe(e),s=tt(t);if(!ts(s)){const l=rs(s),c=F(t),a=`${A}${c}${h.PARENTHESES.LEFT}${l}${h.PARENTHESES.RIGHT}`;return r.value=`${L(r)}${a}`,null}const o=tr(s),i=Ce(t,[o]);return Ce(e,[i])},ns=(e,r)=>{r.value=`${L(r)}${U}${L(e)}`},os=e=>{const r=e.children,t=[];let s=0;for(;s<r.length;){const n=Te(r,s,"currentChild should be specified");if(s===0)t.push(n);else{const o=zt(t);if(re(n)){let i=null,l=ot(n);for(i=n;l;)i=ss(i,o),l=ot(i);if(i!==null){t.push(i);
const c=Oe(i),a=F(c);L(o)===v&&st(a)&&(o.value=es)}}else if(y(n)){const i=V(t)||null;y(i)&&ns(n,o)}}s+=1}return Ce(e,t)},tr=e=>Ce(e,e.children.map(r=>os(r))),is=e=>tr(e),ls="body",rr="No white space is allowed before or after extended pseudo-class name in selector",as=e=>{const r=Kr(e),t={ast:null,pathToBufferNode:[],extendedPseudoNamesStack:[],extendedPseudoBracketsStack:[],standardPseudoNamesStack:[],standardPseudoBracketsStack:[],isAttributeBracketsOpen:!1,attributeBuffer:"",isRegexpOpen:!1,shouldOptimize:!1};
let s=0;for(;s<r.length;){const n=r[s];if(!n)break;const{type:o,value:i}=n,l=r[s+1],c=l?.type,a=l?.value,f=r[s+2],E=f?.value,p=r[s-1],M=p?.type,b=p?.value,H=r[s-2],Bn=H?.value;let u=X(t);switch(o){case C.WORD:if(u===null)be(t,i);else if(we(u))O(t,d.SELECTOR),O(t,d.REGULAR_SELECTOR,i);else if(y(u))S(t,i);else if(re(u)){if(Qt(a)&&E===h.PARENTHESES.LEFT)throw new Error(`${rr}: '${e}'`);const W=i.toLowerCase();t.extendedPseudoNamesStack.push(W),ye(W)?O(t,d.ABSOLUTE_PSEUDO_CLASS,W):(O(t,d.RELATIVE_PSEUDO_CLASS,
W),st(W)&&(t.shouldOptimize=!0))}else I(u)?S(t,i):G(u)&&Ae(t,i);break;case C.MARK:switch(i){case Q:if(!u||typeof u<"u"&&!a)throw new Error(`'${e}' is not a valid selector`);y(u)?t.isAttributeBracketsOpen?S(t,i):D(t,d.SELECTOR_LIST):I(u)?S(t,i):te(u)&&D(t,d.SELECTOR_LIST);break;case U:if(y(u)&&!t.isAttributeBracketsOpen&&(u=Zt(t)),y(u)){if(!t.isAttributeBracketsOpen&&(b===A&&c===C.WORD||M===C.WORD&&a===h.PARENTHESES.LEFT))throw new Error(`'${e}' is not a valid selector`);(!a||qt(c,a)||t.isAttributeBracketsOpen)&&
S(t,i)}I(u)&&S(t,i),G(u)&&Ae(t),te(u)&&qt(c,a)&&O(t,d.REGULAR_SELECTOR);break;case me:case ae:case ce:case ue:case Se:case R:case $:case B:case _:case Ct:case Lt:case h.CURLY.LEFT:case h.CURLY.RIGHT:case v:case Ve:case Ge:case h.SQUARE.LEFT:if(ge.includes(i)){if(u===null)throw new Error(`'${e}' is not a valid selector`);u=Zt(t)}if(u===null)be(t,i),de(i,b)&&(t.isAttributeBracketsOpen=!0);else if(y(u)){if(i===h.CURLY.LEFT&&!(t.isAttributeBracketsOpen||t.isRegexpOpen))throw new Error(`'${e}' is not\
 a valid selector`);S(t,i),de(i,b)&&(t.isAttributeBracketsOpen=!0)}else I(u)?(S(t,i),i===R&&t.extendedPseudoNamesStack.length>0&&(b===R&&Bn===$?t.isRegexpOpen=!1:b&&b!==$&&(qr(t,b,L(u))?t.isRegexpOpen=!t.isRegexpOpen:t.isRegexpOpen=!1))):G(u)?(Ae(t,i),de(i,b)&&(t.isAttributeBracketsOpen=!0)):te(u)?ge.includes(i)?O(t,d.REGULAR_SELECTOR,i):t.isRegexpOpen||(u=nt(t),S(t,i),de(i,b)&&(t.isAttributeBracketsOpen=!0)):we(u)&&(O(t,d.SELECTOR),O(t,d.REGULAR_SELECTOR,i),de(i,b)&&(t.isAttributeBracketsOpen=!0));
break;case h.SQUARE.RIGHT:if(y(u)){if(!t.isAttributeBracketsOpen&&b!==$)throw new Error(`'${e}' is not a valid selector due to '${i}' after '${L(u)}'`);Qr(t)&&(t.isAttributeBracketsOpen=!1,t.attributeBuffer=""),S(t,i)}I(u)&&S(t,i);break;case A:if(Qt(a)&&E&&qe.includes(E))throw new Error(`${rr}: '${e}'`);if(u===null){if(a===Y)be(t,ls);else{if(a===Ke||a===Ye)throw new Error(`${Re} before :${a}() pseudo-class`);be(t,v)}u=X(t)}if(we(u)&&(O(t,d.SELECTOR),O(t,d.REGULAR_SELECTOR),u=X(t)),y(u)&&((b&&ge.
includes(b)||b===Q)&&S(t,v),er(t,e,i,a,E)),te(u)){if(!a)throw new Error(`Invalid colon ':' at the end of selector: '${e}'`);if(rt(a.toLowerCase()))O(t,d.EXTENDED_SELECTOR);else{if(a.toLowerCase()===x)throw new Error(`${K.INVALID_REMOVE}: '${e}'`);u=nt(t),er(t,e,i,c,E)}}if(I(u)){if(F(u)===Y&&a&&qe.includes(a)&&E===h.PARENTHESES.LEFT)throw new Error(`:xpath() pseudo-class should be the last in selector: '${e}'`);S(t,i)}if(G(u)){if(!a)throw new Error(`Invalid pseudo-class arg at the end of selector\
: '${e}'`);Ae(t,v),rt(a.toLowerCase())?(D(t,d.SELECTOR),O(t,d.EXTENDED_SELECTOR)):(S(t,i),E===h.PARENTHESES.LEFT&&t.standardPseudoNamesStack.push(a))}break;case h.PARENTHESES.LEFT:I(u)&&(F(u)!==Y&&t.isRegexpOpen?S(t,i):(t.extendedPseudoBracketsStack.push(i),t.extendedPseudoBracketsStack.length>t.extendedPseudoNamesStack.length&&S(t,i))),y(u)&&(t.standardPseudoNamesStack.length>0&&(S(t,i),t.standardPseudoBracketsStack.push(i)),t.isAttributeBracketsOpen&&S(t,i)),G(u)&&t.extendedPseudoBracketsStack.
push(i);break;case h.PARENTHESES.RIGHT:if(I(u)&&(F(u)!==Y&&t.isRegexpOpen?S(t,i):(t.extendedPseudoBracketsStack.pop(),F(u)!==Y?(t.extendedPseudoNamesStack.pop(),t.extendedPseudoBracketsStack.length>t.extendedPseudoNamesStack.length?S(t,i):t.extendedPseudoBracketsStack.length>=0&&t.extendedPseudoNamesStack.length>=0&&D(t,d.SELECTOR)):t.extendedPseudoBracketsStack.length<t.extendedPseudoNamesStack.length?t.extendedPseudoNamesStack.pop():S(t,i))),y(u))if(t.isAttributeBracketsOpen)S(t,i);else if(t.standardPseudoNamesStack.
length>0&&t.standardPseudoBracketsStack.length>0){S(t,i),t.standardPseudoBracketsStack.pop();const W=t.standardPseudoNamesStack.pop();if(!W)throw new Error(`Parsing error. Invalid selector: ${e}`);if(Object.values(Vt).includes(W)&&a===A&&E&&Xe.includes(E))throw new Error(`Usage of :${E}() pseudo-class is not allowed after any regular pseudo-element: '${W}'`)}else t.extendedPseudoBracketsStack.pop(),t.extendedPseudoNamesStack.pop(),D(t,d.EXTENDED_SELECTOR),D(t,d.SELECTOR);te(u)&&(t.extendedPseudoBracketsStack.
pop(),t.extendedPseudoNamesStack.pop(),D(t,d.EXTENDED_SELECTOR),D(t,d.SELECTOR)),G(u)&&t.extendedPseudoNamesStack.length>0&&t.extendedPseudoBracketsStack.length>0&&(t.extendedPseudoBracketsStack.pop(),t.extendedPseudoNamesStack.pop());break;case ie:case le:case oe:throw new Error(`'${e}' is not a valid selector`);case ne:if(y(u)&&t.isAttributeBracketsOpen)S(t,i);else throw new Error(`'${e}' is not a valid selector`)}break;default:throw new Error(`Unknown type of token: '${i}'`)}s+=1}if(t.ast===null)
throw new Error(`'${e}' is not a valid selector`);if(t.extendedPseudoNamesStack.length>0||t.extendedPseudoBracketsStack.length>0)throw new Error(`Unbalanced brackets for extended pseudo-class: '${V(t.extendedPseudoNamesStack)}'`);if(t.isAttributeBracketsOpen)throw new Error(`Unbalanced attribute brackets in selector: '${e}'`);return t.shouldOptimize?is(t.ast):t.ast},it={MutationObserver:window.MutationObserver||window.WebKitMutationObserver};class cs{constructor(){this.nativeNode=window.Node||Node}setGetter(){
var r;this.getter=(r=Object.getOwnPropertyDescriptor(this.nativeNode.prototype,"textContent"))===null||r===void 0?void 0:r.get}}const lt=new cs,us=e=>lt.getter?lt.getter.apply(e):e.textContent||"",sr=e=>{let r=e.tagName.toLowerCase();return r+=Array.from(e.attributes).map(t=>`[${t.name}="${e.getAttribute(t.name)}"]`).join(""),r},ds=e=>{if(!(e instanceof Element))throw new Error("Function received argument with wrong type");let r;r=e;const t=[];for(;r&&r.nodeType===Node.ELEMENT_NODE;){let s=r.nodeName.
toLowerCase();if(r.id&&typeof r.id=="string"){s+=`#${r.id}`,t.unshift(s);break}let n=r,o=1;for(;n.previousElementSibling;)n=n.previousElementSibling,n.nodeType===Node.ELEMENT_NODE&&n.nodeName.toLowerCase()===s&&(o+=1);o!==1&&(s+=`:nth-of-type(${o})`),t.unshift(s),r=r.parentElement}return t.join(" > ")},at=e=>e instanceof HTMLElement,nr=(e,r)=>{const{parentElement:t}=e;if(!t)throw new Error(r||"Element does no have parent element");return t},fs=e=>typeof e=="object"&&e!==null&&"message"in e&&typeof e.
message=="string",Es=e=>{if(fs(e))return e;try{return new Error(JSON.stringify(e))}catch{return new Error(String(e))}},w=e=>Es(e).message,T={error:typeof console<"u"&&console.error&&console.error.bind?console.error.bind(window.console):console.error,info:typeof console<"u"&&console.info&&console.info.bind?console.info.bind(window.console):console.info},hs=(e,r)=>{const t=e.indexOf(r,e.length-r.length);return t>=0?e.substring(0,t):e},or=(e,r,t)=>e&&e.split(r).join(t),ps=e=>{if(e.startsWith(R)&&e.
endsWith(R))return new RegExp(e.slice(1,-1));const r=e.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(r)},Ss=e=>{let r;switch(e){case void 0:r="undefined";break;case null:r="null";break;default:r=e.toString()}return r},ms=e=>{const r=Number(e);let t;if(!Number.isNaN(r))t=r;else switch(e){case"undefined":t=void 0;break;case"null":t=null;break;case"true":t=!0;break;case"false":t=!1;break;default:t=e}return t},ir=/\sVersion\/(\d{2}\.\d)(.+\s|\s)(Safari)\//.test(navigator.userAgent),gs=e=>!(e.
includes("MSIE")||e.includes("Trident/")),Rs=()=>gs(navigator.userAgent),Le={BACKGROUND:"background",BACKGROUND_IMAGE:"background-image",CONTENT:"content",OPACITY:"opacity"},lr=".*",Ts=/^\s*\/.*\/[gmisuy]*\s*$/,ws=e=>e.replace(/^(["'])([\s\S]*)\1$/,"$2"),ar=e=>{if(!e.includes('url("')){const r=/url\((.*?)\)/g;return e.replace(r,'url("$1")')}return e},cr={regexpArg:e=>{const r=/(\^)?url(\\)?\\\((\w|\[\w)/g;return e.replace(r,'$1url$2\\(\\"?$3')},noneRegexpArg:ar},vs=e=>{const r=[".","+","?","$","\
{","}","(",")","[","]","\\","/"],t=new RegExp(`[${r.join("\\")}]`,"g");return e.replace(t,"\\$&")},Os=e=>{let r;return e.startsWith(R)&&e.endsWith(R)?(r=cr.regexpArg(e),r=r.slice(1,-1)):(r=cr.noneRegexpArg(e),r=r.replace(/\\([\\()[\]"])/g,"$1"),r=vs(r),r=or(r,v,lr)),new RegExp(r,"i")},ys=(e,r)=>{let t="";switch(e){case Le.BACKGROUND:case Le.BACKGROUND_IMAGE:t=ar(r);break;case Le.CONTENT:t=ws(r);break;case Le.OPACITY:t=ir?(Math.round(parseFloat(r)*100)/100).toString():r;break;default:t=r}return t},
bs=(e,r,t)=>{const n=window.getComputedStyle(e,t).getPropertyValue(r);return ys(r,n)},ct=(e,r)=>{const t=e.indexOf(r);let s,n;return t>-1?(s=e.substring(0,t).trim(),n=e.substring(t+1).trim()):s=e,{name:s,value:n}},As=(e,r)=>{const{name:t,value:s}=ct(r,Q);let n=t,o=s;if(Object.values(Vt).includes(t)||(n=null,o=r),!o)throw new Error(`Required style property argument part is missing in :${e}() arg: '${r}'`);return n&&(n=`${A}${A}${n}`),{regularPseudoElement:n,styleMatchArg:o}},Cs=e=>{const{pseudoName:r,
pseudoArg:t,domElement:s}=e,{regularPseudoElement:n,styleMatchArg:o}=As(r,t),{name:i,value:l}=ct(o,A);if(!i||!l)throw new Error(`Required property name or value is missing in :${r}() arg: '${o}'`);let c;try{c=Os(l)}catch(f){throw T.error(w(f)),new Error(`Invalid argument of :${r}() pseudo-class: '${o}'`)}const a=bs(s,i,n);return c&&c.test(a)},Ls=e=>!(e.includes(R)||!/^[\w-]+$/.test(e)),Pe=function(e){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1,t;if(e.length>1&&e.startsWith(_)&&
e.endsWith(_)&&(e=e.slice(1,-1)),e==="")throw new Error("Argument should be specified. Empty arg is invalid.");if(e.startsWith(R)&&e.endsWith(R))if(e.length>2)t=ps(e);else throw new Error(`Invalid regexp: '${e}'`);else if(e.includes(v)){if(e===v&&!r)throw new Error(`Argument should be more specific than ${e}`);t=or(e,v,lr),t=new RegExp(t)}else{if(!Ls(e))throw new Error(`Invalid argument: '${e}'`);t=e}return t},ur=(e,r)=>{const{name:t,value:s}=ct(r,J);if(!t)throw new Error(`Required attribute nam\
e is missing in :${e} arg: ${r}`);return{rawName:t,rawValue:s}},Ps=e=>{const{pseudoName:r,pseudoArg:t,domElement:s}=e,n=s.attributes;if(n.length===0)return!1;const{rawName:o,rawValue:i}=ur(r,t);let l;try{l=Pe(o)}catch(f){const E=w(f);throw T.error(E),new SyntaxError(E)}let c=!1,a=0;for(;a<n.length&&!c;){const f=n[a];if(!f)break;const E=l instanceof RegExp?l.test(f.name):l===f.name;if(!i)c=E;else{let p;try{p=Pe(i)}catch(b){const H=w(b);throw T.error(H),new SyntaxError(H)}const M=p instanceof RegExp?
p.test(f.value):p===f.value;c=E&&M}a+=1}return c},_s=e=>{e.length>1&&e.startsWith(_)&&e.endsWith(_)&&(e=e.slice(1,-1));const r=e.split(xe),t=[];let s="",n=!1,o=0;for(;o<r.length;){const l=Te(r,o,`Invalid pseudo-class arg: '${e}'`);l.startsWith(R)&&l.endsWith(R)&&l.length>2?t.push(l):l.startsWith(R)?(n=!0,s+=l):l.endsWith(R)?(n=!1,s+=`.${l}`,t.push(s),s=""):n?s+=l:t.push(l),o+=1}if(s.length>0)throw new Error(`Invalid regexp property pattern '${e}'`);return t.map(l=>{if(l.length===0)throw new Error(
`Empty pattern '${l}' is invalid in chain '${e}'`);let c;try{c=Pe(l,!0)}catch(a){throw T.error(w(a)),new Error(`Invalid property pattern '${l}' in property chain '${e}'`)}return c})},ut=function(e,r){let t=arguments.length>2&&arguments[2]!==void 0?arguments[2]:[];const s=ee(r);if(r.length===1){let o;for(o in e)s instanceof RegExp?s.test(o)&&t.push({base:e,prop:o,value:e[o]}):s===o&&t.push({base:e,prop:s,value:e[o]});return t}if(s instanceof RegExp){const o=r.slice(1),i=[];for(const l in e)s.test(
l)&&i.push(l);i.forEach(l=>{var c;const a=(c=Object.getOwnPropertyDescriptor(e,l))===null||c===void 0?void 0:c.value;ut(a,o,t)})}if(e&&typeof s=="string"){var n;const o=(n=Object.getOwnPropertyDescriptor(e,s))===null||n===void 0?void 0:n.value;r=r.slice(1),o!==void 0&&ut(o,r,t)}return t},Ns=e=>{const{pseudoName:r,pseudoArg:t,domElement:s}=e,{rawName:n,rawValue:o}=ur(r,t);if(n.includes("\\/")||n.includes("\\."))throw new Error(`Invalid :${r} name pattern: ${n}`);let i;try{i=_s(n)}catch(f){const E=w(
f);throw T.error(E),new SyntaxError(E)}const l=ut(s,i);if(l.length===0)return!1;let c=!0;if(o){let f;try{f=Pe(o)}catch(E){const p=w(E);throw T.error(p),new SyntaxError(p)}if(f)for(let E=0;E<l.length;E+=1){var a;const p=(a=l[E])===null||a===void 0?void 0:a.value;if(f instanceof RegExp)c=f.test(Ss(p));else{if(p==="null"||p==="undefined"){c=f===p;break}c=ms(f)===p}if(c)break}}return c},$s=e=>{const{pseudoName:r,pseudoArg:t,domElement:s}=e,n=us(s);let o,i=t;if(i.startsWith(R)&&Ts.test(i)){const l=i.
lastIndexOf("/"),c=i.substring(l+1);i=i.substring(0,l+1).slice(1,-1).replace(/\\([\\"])/g,"$1");let a;try{a=new RegExp(i,c)}catch{throw new Error(`Invalid argument of :${r}() pseudo-class: ${t}`)}o=a.test(n)}else i=i.replace(/\\([\\()[\]"])/g,"$1"),o=n.includes(i);return o},Is=(e,r)=>{const t=Number(e);if(Number.isNaN(t)||t<1||t>=256)throw new Error(`Invalid argument of :${r} pseudo-class: '${e}'`);return t},ks=(e,r,t)=>{let s=null,n=0;for(;n<r;){if(s=e.parentElement,!s)throw new Error(`Out of D\
OM: Argument of :${t}() pseudo-class is too big \u2014 '${r}'.`);e=s,n+=1}return s},Ds=e=>{let r;try{document.querySelectorAll(e),r=!0}catch{r=!1}return r},Ms=(e,r,t)=>{let s;try{s=e(r)}catch(n){throw T.error(w(n)),new Error(t)}return s},_e=(e,r,t)=>`${Mr} ${e}, may be invalid :${r}() pseudo-class arg: '${t}'`,Us=(e,r,t)=>{let s,n,o;switch(r){case Fe:case He:case We:o=$s,s={pseudoName:r,pseudoArg:t,domElement:e},n=_e("text content",r,t);break;case Nt:case It:case $t:o=Cs,s={pseudoName:r,pseudoArg:t,
domElement:e},n=_e("style",r,t);break;case kt:o=Ps,s={domElement:e,pseudoName:r,pseudoArg:t},n=_e("attributes",r,t);break;case Dt:o=Ns,s={domElement:e,pseudoName:r,pseudoArg:t},n=_e("properties",r,t);break;default:throw new Error(`Unknown absolute pseudo-class :${r}()`)}return Ms(o,s,n)},Ne={nthAncestor:(e,r,t)=>{const s=Is(r,t);return e.map(o=>{let i=null;try{i=ks(o,s,t)}catch(l){T.error(w(l))}return i}).filter(at)},xpath:(e,r)=>{const t=e.map(s=>{const n=[];let o;try{o=document.evaluate(r,s,null,
window.XPathResult.UNORDERED_NODE_ITERATOR_TYPE,null)}catch(l){throw T.error(w(l)),new Error(`Invalid argument of :xpath() pseudo-class: '${r}'`)}let i=o.iterateNext();for(;i;)at(i)&&n.push(i),i=o.iterateNext();return n});return et(t)},upward:(e,r)=>{if(!Ds(r))throw new Error(`Invalid argument of :upward pseudo-class: '${r}'`);return e.map(s=>{const n=s.parentElement;return n?n.closest(r):null}).filter(at)}},$e=`${Qe}${ae}`,dt=`${Qe}${me}`,ft=(e,r)=>zr(e.children,`RegularSelector is missing for \
:${r}() pseudo-class`),Bs=e=>{const{element:r,relativeSelectorList:t,pseudoName:s}=e;return t.children.every(n=>{const o=ft(n,s);let i="",l=null;const c=L(o);if(c.startsWith(ce)||c.startsWith(ue)){l=r.parentElement;const f=sr(r);i=`${$e}${f}${c}`}else c===v?(l=r,i=`${dt}${v}`):(i=`${dt}${c}`,l=r);if(!l)throw new Error(`Selection by :${s}() pseudo-class is not possible`);let a;try{a=ke(n,l,i)}catch(f){throw T.error(w(f)),new Error(`Invalid selector for :${s}() pseudo-class: '${c}'`)}return a.length>
0})},xs=e=>{const{element:r,relativeSelectorList:t,pseudoName:s}=e;return t.children.some(n=>{const o=ft(n,s),i=nr(r,`Selection by :${s}() pseudo-class is not possible`),l=`${$e}${L(o)}`;let c;try{c=ke(n,i,l)}catch{return!1}return c.includes(r)})},Vs=e=>{const{element:r,relativeSelectorList:t,pseudoName:s}=e;return t.children.every(n=>{const o=ft(n,s),i=nr(r,`Selection by :${s}() pseudo-class is not possible`),l=`${$e}${L(o)}`;let c;try{c=ke(n,i,l)}catch(a){throw T.error(w(a)),new Error(`Invalid\
 selector for :${s}() pseudo-class: '${L(o)}'`)}return!c.includes(r)})},Ie=(e,r,t)=>{const s=t||L(e);let n=[];try{n=Array.from(r.querySelectorAll(s))}catch(o){throw new Error(`Error: unable to select by '${s}' \u2014 ${w(o)}`)}return n},Gs=(e,r)=>{let t=[];const s=Oe(r),n=F(s);if(ye(n)){const o=L(s,`Missing arg for :${n}() pseudo-class`);if(n===Ye)t=Ne.nthAncestor(e,o,n);else if(n===Y){try{document.createExpression(o,null)}catch{throw new Error(`Invalid argument of :${n}() pseudo-class: '${o}'`)}
t=Ne.xpath(e,o)}else n===Ke?Number.isNaN(Number(o))?t=Ne.upward(e,o):t=Ne.nthAncestor(e,o,n):t=e.filter(i=>Us(i,n,o))}else if(Jt(n)){const o=tt(s);let i;switch(n){case Mt:case Ut:i=l=>Bs({element:l,relativeSelectorList:o,pseudoName:n});break;case ze:i=l=>xs({element:l,relativeSelectorList:o,pseudoName:n});break;case je:i=l=>Vs({element:l,relativeSelectorList:o,pseudoName:n});break;default:throw new Error(`Unknown relative pseudo-class: '${n}'`)}t=e.filter(i)}else throw new Error(`Unknown extende\
d pseudo-class: '${n}'`);return t},Fs=(e,r)=>{let t=[];const s=L(r);return s.startsWith(ae)?t=e.map(n=>{const o=`${Qe}${s}`;return Ie(r,n,o)}):s.startsWith(ce)||s.startsWith(ue)?t=e.map(n=>{const o=n.parentElement;if(!o)return[];const i=sr(n),l=`${$e}${i}${s}`;return Ie(r,o,l)}):t=e.map(n=>{const o=`${dt}${L(r)}`;return Ie(r,n,o)}),et(t)},ke=(e,r,t)=>{let s=[],n=0;for(;n<e.children.length;){const o=Te(e.children,n,"selectorNodeChild should be specified");n===0?s=Ie(o,r,t):re(o)?s=Gs(s,o):y(o)&&(s=
Fs(s,o)),n+=1}return s},dr=function(e){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:document;const t=[];return e.children.forEach(n=>{t.push(...ke(n,r))}),[...new Set(et(t))]};class Hs{constructor(){this.astCache=new Map}saveAstToCache(r,t){this.astCache.set(r,t)}getAstFromCache(r){return this.astCache.get(r)||null}getSelectorAst(r){let t=this.getAstFromCache(r);return t||(t=as(r)),this.saveAstToCache(r,t),t}querySelectorAll(r){const t=this.getSelectorAst(r);return dr(t)}}const Et=new Hs,
Ws=e=>{const r={};return e.forEach(t=>{const[s,n]=t;r[s]=n}),r},fr="debug",ht=e=>{const r=`${A}${x}${h.PARENTHESES.LEFT}${h.PARENTHESES.RIGHT}`,t=`${A}${x}${h.PARENTHESES.LEFT}`;let s,n=!1;const o=e.indexOf(r);if(o===0)throw new Error(`${K.NO_TARGET_SELECTOR}: '${e}'`);if(o>0){if(o!==e.lastIndexOf(r))throw new Error(`${K.MULTIPLE_USAGE}: '${e}'`);if(o+r.length<e.length)throw new Error(`${K.INVALID_POSITION}: '${e}'`);s=e.substring(0,o),n=!0}else{if(e.includes(t))throw new Error(`${K.INVALID_REMOVE}\
: '${e}'`);s=e}return{selector:s,stylesOfSelector:n?[{property:x,value:Z}]:[]}},Er=(e,r)=>{let t=e.trim();if(t.startsWith(Gt))throw new Error(`${Ht}: '${t}'.`);let s;try{s=ht(t)}catch(l){throw T.error(w(l)),new Error(`${K.INVALID_REMOVE}: '${t}'`)}let n=[],o=!1,i;try{t=s.selector,n=s.stylesOfSelector,i=r.getSelectorAst(t),o=!0}catch{o=!1}return{success:o,selector:t,ast:i,stylesOfSelector:n}},hr=()=>new Map,pt=(e,r)=>{const{selector:t,ast:s,rawStyles:n}=r;if(!n)throw new Error(`No style declarati\
on for selector: '${t}'`);if(!s)throw new Error(`No ast parsed for selector: '${t}'`);const o=e.get(t);o?o.styles.push(...n):e.set(t,{ast:s,styles:n})},Ys=e=>e.some(r=>r.property===x&&r.value===Z),Ks=e=>{const r=e.find(t=>t.property===fr);return r?.value},Xs=e=>{const{selector:r,ast:t,rawStyles:s}=e;if(!t)throw new Error(`AST should be parsed for selector: '${r}'`);if(!s)throw new Error(`Styles should be parsed for selector: '${r}'`);const n={selector:r,ast:t},o=Ks(s),i=Ys(s);let l=s;if(o&&(l=s.
filter(c=>c.property!==fr),(o===Z||o===Ft)&&(n.debug=o)),i){n.style={[x]:Z};const c=l.find(a=>a.property===Je);c&&(n.style[Je]=c.value)}else if(l.length>0){const c=l.map(f=>{const{property:E,value:p}=f;return[E,p]}),a=Ws(c);n.style=a}return n},pr=e=>{const r=[];return e.forEach((t,s)=>{const n=s,{ast:o,styles:i}=t;r.push(Xs({selector:n,ast:o,rawStyles:i}))}),r},zs=e=>{const r=e.trim();return Ze(r,Ir)},fe={PROPERTY:"property",VALUE:"value"},De=e=>e.bufferValue!==""&&e.valueQuoteMark!==null,Sr=e=>{
e.styles.push({property:e.bufferProperty.trim(),value:e.bufferValue.trim()}),e.bufferProperty="",e.bufferValue=""},js=(e,r,t)=>{const{value:s}=t;switch(t.type){case C.WORD:if(e.bufferProperty.length>0)throw new Error(`Invalid style property in style block: '${r}'`);e.bufferProperty+=s;break;case C.MARK:if(s===A){if(e.bufferProperty.trim().length===0)throw new Error(`Missing style property before ':' in style block: '${r}'`);e.bufferProperty=e.bufferProperty.trim(),e.processing=fe.VALUE}else if(!Pt.
includes(s))throw new Error(`Invalid style declaration in style block: '${r}'`);break;default:throw new Error(`Unsupported style property character: '${s}' in style block: '${r}'`)}},qs=(e,r,t)=>{const{value:s}=t;if(t.type===C.WORD)e.bufferValue+=s;else switch(s){case A:if(!De(e))throw new Error(`Invalid style value for property '${e.bufferProperty}' in style block: '${r}'`);e.bufferValue+=s;break;case Se:De(e)?e.bufferValue+=s:(Sr(e),e.processing=fe.PROPERTY);break;case B:case _:e.valueQuoteMark===
null?e.valueQuoteMark=s:!e.bufferValue.endsWith($)&&e.valueQuoteMark===s&&(e.valueQuoteMark=null),e.bufferValue+=s;break;case $:if(!De(e))throw new Error(`Invalid style value for property '${e.bufferProperty}' in style block: '${r}'`);e.bufferValue+=s;break;case U:case ne:case oe:case ie:case le:e.bufferValue.length>0&&(e.bufferValue+=s);break;default:throw new Error(`Unknown style declaration token: '${s}'`)}},Qs=e=>{const r=e.trim(),t=zs(r),s={processing:fe.PROPERTY,styles:[],bufferProperty:"",
bufferValue:"",valueQuoteMark:null};let n=0;for(;n<t.length;){const o=t[n];if(!o)break;if(s.processing===fe.PROPERTY)js(s,r,o);else if(s.processing===fe.VALUE)qs(s,r,o);else throw new Error("Style declaration parsing failed");n+=1}if(De(s))throw new Error(`Unbalanced style declaration quotes in style block: '${r}'`);if(s.bufferProperty.length>0){if(s.bufferValue.length===0)throw new Error(`Missing style value for property '${s.bufferProperty}' in style block '${r}'`);Sr(s)}if(s.styles.length===0)
throw new Error(P.NO_STYLE);return s.styles},Js=e=>{const r=[];for(let t=0;t<e.length;t+=1)e[t]===h.CURLY.LEFT&&r.push(t);return r},Zs=(e,r)=>{var t;const s=e.trim();if(s.includes(`${R}${v}`)&&s.includes(`${v}${R}`))throw new Error(P.NO_COMMENT);const n=Js(s);if(ee(n)===0)throw new Error(Re);let o;if(n.length>0&&!s.includes(h.CURLY.RIGHT))throw new Error(`${P.NO_STYLE} OR ${P.UNCLOSED_STYLE}`);if(n.length===0||!s.includes(h.CURLY.RIGHT))try{if(o=Er(s,r),o.success){var i;if(((i=o.stylesOfSelector)===
null||i===void 0?void 0:i.length)===0)throw new Error(P.NO_STYLE_OR_REMOVE);return{selector:o.selector.trim(),ast:o.ast,rawStyles:o.stylesOfSelector}}else throw new Error("Invalid selector")}catch(E){throw new Error(w(E))}let l,c;const a={selector:""};for(let E=n.length-1;E>-1;E-=1){const p=n[E];if(!p)throw new Error(`Impossible to continue, no '{' to process for rule: '${s}'`);if(l=s.slice(0,p),c=s.slice(p+1,s.length-1),o=Er(l,r),o.success){var f;a.selector=o.selector.trim(),a.ast=o.ast,a.rawStyles=
o.stylesOfSelector;const M=Qs(c);(f=a.rawStyles)===null||f===void 0||f.push(...M);break}else continue}if(((t=a.selector)===null||t===void 0?void 0:t.length)===0)throw new Error("Selector in not valid");return a},en=(e,r)=>{const t=hr(),s=[];return[...new Set(e.map(o=>o.trim()))].forEach(o=>{try{pt(t,Zs(o,r))}catch(i){const l=w(i);s.push(`'${o}' - error: '${l}'`)}}),s.length>0&&T.info(`Invalid rules:
  ${s.join(`
  `)}`),pr(t)},mr=/[;}]/g,gr=/[;:}]/g,Rr=/\S/g,Tr=e=>{e.rawRuleData={selector:""}},tn=(e,r)=>{let t=e.selectorBuffer.trim();if(t.startsWith(Gt))throw new Error(`${Ht}: '${t}'.`);let s;try{s=ht(t)}catch(l){throw T.error(w(l)),new Error(`${K.INVALID_REMOVE}: '${t}'`)}if(e.nextIndex===-1){if(t===s.selector)throw new Error(`${P.NO_STYLE_OR_REMOVE}: '${e.cssToParse}'`);e.cssToParse=""}let n=[],o=!1,i;try{t=s.selector,n=s.stylesOfSelector,i=r.getSelectorAst(t),o=!0}catch{o=!1}return e.nextIndex>0&&(e.
cssToParse=e.cssToParse.slice(e.nextIndex)),{success:o,selector:t,ast:i,stylesOfSelector:n}},wr=(e,r)=>{gr.lastIndex=e.nextIndex;let t=gr.exec(e.cssToParse);if(t===null)throw new Error(`${P.INVALID_STYLE}: '${e.cssToParse}'`);let s=t.index,n=t[0];if(n===h.CURLY.RIGHT){if(e.cssToParse.slice(e.nextIndex,s).trim().length===0){if(r.length===0)throw new Error(`${P.NO_STYLE}: '${e.cssToParse}'`)}else throw new Error(`${P.INVALID_STYLE}: '${e.cssToParse}'`);return s}if(n===A){const o=s;if(mr.lastIndex=
o,t=mr.exec(e.cssToParse),t===null)throw new Error(`${P.UNCLOSED_STYLE}: '${e.cssToParse}'`);s=t.index,n=t[0];const i=e.cssToParse.slice(e.nextIndex,o).trim();if(i.length===0)throw new Error(`${P.NO_PROPERTY}: '${e.cssToParse}'`);const l=e.cssToParse.slice(o+1,s).trim();if(l.length===0)throw new Error(`${P.NO_VALUE}: '${e.cssToParse}'`);if(r.push({property:i,value:l}),n===h.CURLY.RIGHT)return s}return e.cssToParse=e.cssToParse.slice(s+1),e.nextIndex=0,wr(e,r)},rn=e=>{const r=[],t=wr(e,r);Rr.lastIndex=
t+1;const s=Rr.exec(e.cssToParse);if(s===null)return e.cssToParse="",r;const n=s.index;return e.cssToParse=e.cssToParse.slice(n),r},sn=(e,r)=>{const t=e.trim();if(t.includes(`${R}${v}`)&&t.includes(`${v}${R}`))throw new Error(`${P.NO_COMMENT} in stylesheet: '${t}'`);const s={isSelector:!0,nextIndex:0,cssToParse:t,selectorBuffer:"",rawRuleData:{selector:""}},n=hr();let o;for(;s.cssToParse;)if(s.isSelector){if(s.nextIndex=s.cssToParse.indexOf(h.CURLY.LEFT),s.selectorBuffer.length===0&&s.nextIndex===
0)throw new Error(`${P.NO_SELECTOR}: '${s.cssToParse}'`);s.nextIndex===-1?s.selectorBuffer=s.cssToParse:s.selectorBuffer+=s.cssToParse.slice(0,s.nextIndex),o=tn(s,r),o.success?(s.rawRuleData.selector=o.selector.trim(),s.rawRuleData.ast=o.ast,s.rawRuleData.rawStyles=o.stylesOfSelector,s.isSelector=!1,s.nextIndex===-1?(pt(n,s.rawRuleData),Tr(s)):(s.nextIndex=1,s.selectorBuffer="")):(s.selectorBuffer+=h.CURLY.LEFT,s.cssToParse=s.cssToParse.slice(1))}else{var i;const l=rn(s);(i=s.rawRuleData.rawStyles)===
null||i===void 0||i.push(...l),pt(n,s.rawRuleData),s.nextIndex=0,Tr(s),s.isSelector=!0}return pr(n)},St=e=>typeof e=="number"&&!Number.isNaN(e);class Ee{constructor(r){this.callback=r,this.executeCallback=this.executeCallback.bind(this)}executeCallback(){this.lastRunTime=performance.now(),St(this.timerId)&&(clearTimeout(this.timerId),delete this.timerId),this.callback()}run(){if(!St(this.timerId)){if(St(this.lastRunTime)){const r=performance.now()-this.lastRunTime;if(r<Ee.THROTTLE_DELAY_MS){this.
timerId=window.setTimeout(this.executeCallback,Ee.THROTTLE_DELAY_MS-r);return}}this.timerId=window.setTimeout(this.executeCallback)}}}g(Ee,"THROTTLE_DELAY_MS",150);const nn=10,on=["mouseover","mouseleave","mouseenter","mouseout"],vr=["keydown","keypress","keyup","auxclick","click","contextmenu","dblclick","mousedown","mouseenter","mouseleave","mousemove","mouseover","mouseout","mouseup","pointerlockchange","pointerlockerror","select","wheel"],ln=["wheel"];class an{constructor(){g(this,"getLastEv\
entType",()=>this.lastEventType),g(this,"getTimeSinceLastEvent",()=>this.lastEventTime?Date.now()-this.lastEventTime:null),this.trackedEvents=ir?vr.filter(r=>!ln.includes(r)):vr,this.trackedEvents.forEach(r=>{document.documentElement.addEventListener(r,this.trackEvent,!0)})}trackEvent(r){this.lastEventType=r.type,this.lastEventTime=Date.now()}isIgnoredEventType(){const r=this.getLastEventType(),t=this.getTimeSinceLastEvent();return!!r&&on.includes(r)&&!!t&&t<nn}stopTracking(){this.trackedEvents.
forEach(r=>{document.documentElement.removeEventListener(r,this.trackEvent,!0)})}}function cn(e){return!e.some(r=>r.type!=="attributes")}function un(e){e.isDomObserved||(e.isDomObserved=!0,e.domMutationObserver=new it.MutationObserver(r=>{if(!r||r.length===0)return;const t=new an;t.isIgnoredEventType()&&cn(r)||(e.eventTracker=t,e.scheduler.run())}),e.domMutationObserver.observe(document,{childList:!0,subtree:!0,attributes:!0,attributeFilter:["id","class"]}))}function Or(e){e.isDomObserved&&(e.isDomObserved=
!1,e.domMutationObserver&&e.domMutationObserver.disconnect(),e.eventTracker&&e.eventTracker.stopTracking())}const dn=/^("|')adguard.+?/,fn=(e,r)=>{const{node:t}=r;r.removed=!0;const s=ds(t),n=e.removalsStatistic[s]||0;if(n>Wt){T.error(`ExtendedCss: infinite loop protection for selector: '${s}'`);return}t.parentElement&&(t.parentElement.removeChild(t),e.removalsStatistic[s]=n+1)},yr=(e,r)=>{e instanceof HTMLElement&&Object.keys(r).forEach(t=>{if(typeof e.style.getPropertyValue(t.toString())<"u"){
let s=r[t];if(!s||t===Je&&s.match(dn))return;s=hs(s.trim(),"!important").trim(),e.style.setProperty(t,s,"important")}})},En=e=>"node"in e&&"rules"in e&&e.rules instanceof Array,hn=e=>"node"in e&&"originalStyle"in e&&"rules"in e&&e.rules instanceof Array,br=(e,r)=>{if(r.protectionObserver)return;let t;if(e.beforeStyleApplied){if(!En(r))throw new Error("Returned IAffectedElement should have 'node' and 'rules' properties");if(t=e.beforeStyleApplied(r),!t)throw new Error("Callback 'beforeStyleApplie\
d' should return IAffectedElement")}else t=r;if(!hn(t))throw new Error("Returned IAffectedElement should have 'node' and 'rules' properties");const{node:s,rules:n}=t;for(let o=0;o<n.length;o+=1){const i=n[o],l=i?.selector,c=i?.style,a=i?.debug;if(c){if(c[x]===Z){fn(e,t);return}yr(s,c)}else if(!a)throw new Error(`No style declaration in rule for selector: '${l}'`)}},Ar=e=>{e.protectionObserver&&e.protectionObserver.disconnect(),e.node.style.cssText=e.originalStyle};class pn{constructor(r){this.styleProtectionCount=
0,this.observer=new it.MutationObserver(t=>{t.length&&(this.styleProtectionCount+=1,r(t,this))})}observe(r,t){this.styleProtectionCount<Wt?this.observer.observe(r,t):T.error("ExtendedCss: infinite loop protection for style")}disconnect(){this.observer.disconnect()}}const Cr={attributes:!0,attributeOldValue:!0,attributeFilter:["style"]},Sn=e=>(t,s)=>{if(!t[0])return;const{target:n}=t[0];s.disconnect(),e.forEach(o=>{yr(n,o)}),s.observe(n,Cr)},mn=(e,r)=>{if(!it.MutationObserver)return null;const t=[];
r.forEach(n=>{const{style:o}=n;o&&t.push(o)});const s=new pn(Sn(t));return s.observe(e,Cr),s},gn=4;class Rn{constructor(){this.appliesTimings=[],this.appliesCount=0,this.timingsSum=0,this.meanTiming=0,this.squaredSum=0,this.standardDeviation=0}push(r){this.appliesTimings.push(r),this.appliesCount+=1,this.timingsSum+=r,this.meanTiming=this.timingsSum/this.appliesCount,this.squaredSum+=r*r,this.standardDeviation=Math.sqrt(this.squaredSum/this.appliesCount-Math.pow(this.meanTiming,2))}}const he=e=>Number(
e.toFixed(gn)),Tn=e=>({appliesTimings:e.appliesTimings.map(r=>he(r)),appliesCount:he(e.appliesCount),timingsSum:he(e.timingsSum),meanTiming:he(e.meanTiming),standardDeviation:he(e.standardDeviation)}),wn=e=>{if(e.areTimingsPrinted)return;e.areTimingsPrinted=!0;const r={};e.parsedRules.forEach(t=>{if(t.timingStats){const{selector:s,style:n,debug:o,matchedElements:i}=t;if(!n&&!o)throw new Error(`Rule should have style declaration for selector: '${s}'`);const l={selectorParsed:s,timings:Tn(t.timingStats)};
n&&n[x]===Z?l.removed=!0:(l.styleApplied=n||null,l.matchedElements=i),r[s]=l}}),Object.keys(r).length!==0&&T.info(`[ExtendedCss] Timings in milliseconds for %o:
%o`,window.location.href,r)},vn=(e,r)=>e.find(t=>t.node===r),On=(e,r)=>{const t=!!r.debug||e.debug;let s;t&&(s=performance.now());const{ast:n}=r,o=[];try{o.push(...dr(n))}catch(i){e.debug&&T.error(w(i))}if(o.forEach(i=>{let l=vn(e.affectedElements,i);if(l)l.rules.push(r),br(e,l);else{const c=i.style.cssText;l={node:i,rules:[r],originalStyle:c,protectionObserver:null},br(e,l),e.affectedElements.push(l)}}),t&&s){const i=performance.now()-s;r.timingStats||(r.timingStats=new Rn),r.timingStats.push(i)}
return o},Lr=e=>{const r=[];Or(e),e.parsedRules.forEach(s=>{const n=On(e,s);Array.prototype.push.apply(r,n),s.debug&&(s.matchedElements=n)});let t=e.affectedElements.length;for(;t;){const s=e.affectedElements[t-1];if(!s)break;r.includes(s.node)?s.removed||s.protectionObserver||(s.protectionObserver=mn(s.node,s.rules)):(Ar(s),e.affectedElements.splice(t-1,1)),t-=1}un(e),wn(e)};class mt{constructor(r){if(!r)throw new Error("ExtendedCss configuration should be provided.");if(this.applyRulesCallbackListener=
this.applyRulesCallbackListener.bind(this),this.context={beforeStyleApplied:r.beforeStyleApplied,debug:!1,affectedElements:[],isDomObserved:!1,removalsStatistic:{},parsedRules:[],scheduler:new Ee(this.applyRulesCallbackListener)},!Rs()){T.error("Browser is not supported by ExtendedCss");return}if(!r.styleSheet&&!r.cssRules)throw new Error("ExtendedCss configuration should have 'styleSheet' or 'cssRules' defined.");if(r.styleSheet)try{this.context.parsedRules.push(...sn(r.styleSheet,Et))}catch(t){
throw new Error(`Pass the rules as configuration.cssRules since configuration.styleSheet cannot be parsed because of: '${w(t)}'`)}if(r.cssRules&&this.context.parsedRules.push(...en(r.cssRules,Et)),this.context.debug=r.debug||this.context.parsedRules.some(t=>t.debug===Ft),this.context.beforeStyleApplied&&typeof this.context.beforeStyleApplied!="function")throw new Error(`Invalid configuration. Type of 'beforeStyleApplied' should be a function, received: '${typeof this.context.beforeStyleApplied}'`)}applyRulesCallbackListener(){
Lr(this.context)}init(){lt.setGetter()}apply(){Lr(this.context),document.readyState!=="complete"&&document.addEventListener("DOMContentLoaded",this.applyRulesCallbackListener,!1)}dispose(){Or(this.context),this.context.affectedElements.forEach(r=>{Ar(r)}),document.removeEventListener("DOMContentLoaded",this.applyRulesCallbackListener,!1)}getAffectedElements(){return this.context.affectedElements}static query(r){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!0;if(typeof r!="string")
throw new Error("Selector should be defined as a string.");const s=performance.now();try{return Et.querySelectorAll(r)}finally{const n=performance.now();t||T.info(`[ExtendedCss] Elapsed: ${Math.round((n-s)*1e3)} \u03BCs.`)}}static validate(r){try{const{selector:t}=ht(r);return mt.query(t),{ok:!0,error:null}}catch(t){return{ok:!1,error:`Error: Invalid selector: '${r}' -- ${w(t)}`}}}}var z;(function(e){e[e.Debug=2]="Debug",e[e.Info=1]="Info",e[e.Error=0]="Error"})(z||(z={}));const yn=()=>`[${new Date().
toISOString()}]`,bn=e=>{if(e instanceof Error)return e.stack||e.message||String(e);if(typeof e=="string")return e;try{return JSON.stringify(e)}catch{return String(e)}},gt=(e,r)=>[yn(),e,...r.map(bn)].join(" ");class An{constructor(r,t){_defineProperty2(this,"prefix","[Safari Extension]"),_defineProperty2(this,"loggingLevel",z.Info),this.prefix=r,this.loggingLevel=t}get level(){return this.loggingLevel}set level(r){this.loggingLevel=r}debug(){if(this.loggingLevel>=z.Debug){for(var r=arguments.length,
t=new Array(r),s=0;s<r;s++)t[s]=arguments[s];console.debug(gt(this.prefix,t))}}info(){if(this.loggingLevel>=z.Info){for(var r=arguments.length,t=new Array(r),s=0;s<r;s++)t[s]=arguments[s];console.info(gt(this.prefix,t))}}error(){if(this.loggingLevel>=z.Error){for(var r=arguments.length,t=new Array(r),s=0;s<r;s++)t[s]=arguments[s];console.error(gt(this.prefix,t))}}}class Cn{constructor(){_defineProperty2(this,"level",z.Debug)}debug(){}info(){}error(){}}let se=new Cn;class Ln{get level(){return se.
level}set level(r){se.level=r}debug(){se.debug(...arguments)}info(){se.info(...arguments)}error(){se.error(...arguments)}}const Pn=e=>{se=e},Rt=new Ln,Vn="4.3.0",Pr=e=>e.map(r=>r.trim()).filter(r=>r.length>0).map(r=>r.at(-1)!=="}"?`${r} {display:none!important;}`:r),_n=e=>{const r=document.createElement("script");return r.setAttribute("type","text/javascript"),r.textContent=e,(document.head||document.documentElement).appendChild(r),r.parentNode?(r.parentNode.removeChild(r),!1):!0},Nn=e=>{const r=new Blob(
[e],{type:"text/javascript"}),t=URL.createObjectURL(r),s=document.createElement("script");return s.src=t,(document.head||document.documentElement).appendChild(s),URL.revokeObjectURL(t),s.parentNode?(s.parentNode.removeChild(s),!1):!0},_r=function(){let e=arguments.length>0&&arguments[0]!==void 0?arguments[0]:[];e.unshift("( function () { try {"),e.push(";document.currentScript && document.currentScript.remove();"),e.push("} catch (ex) { console.error('[WBLOCK_PAGE_SCRIPT_EXECUTION_FAILED] ' + ex\
); } })();");const r=e.join(`\r
`);_n(r)||Nn(r)||console.warn("[WBLOCK_PAGE_SCRIPT_INJECTION_BLOCKED] Page script injection was blocked; continuing without page-context scripts.")},$n=e=>{const{MutationObserver:r}=window;if(!r)return;new r(s=>{for(let n=0;n<s.length;n+=1){const o=s[n];if(e.hasAttribute("mod")&&e.getAttribute("mod")==="inner"){e.removeAttribute("mod");break}e.setAttribute("mod","inner");let i=!1;if(o.removedNodes.length>0)for(let l=0;l<o.removedNodes.length;l+=1)i=!0,e.appendChild(o.removedNodes[l]);else o.oldValue&&
(i=!0,e.textContent=o.oldValue);i||e.removeAttribute("mod")}}).observe(e,{childList:!0,characterData:!0,subtree:!0,characterDataOldValue:!0})};class In{applyConfiguration(r){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1;this.insertCss(r.css),this.insertExtendedCss(r.extendedCss),this.runScriptlets(r.scriptlets,t),this.runScripts(r.js)}insertCss(r){if(!(!r||!r.length))try{const t=document.createElement("style");if(t.setAttribute("type","text/css"),(document.head||document.documentElement).
appendChild(t),t.sheet){const s=Pr(r);for(const n of s)t.sheet.insertRule(n)}$n(t)}catch(t){Rt.error("Failed to insert CSS",t)}}insertExtendedCss(r){if(!(!r||!r.length))try{const t=Pr(r);new mt({cssRules:t}).apply()}catch(t){Rt.error("Failed to insert extended CSS",t)}}runScripts(r){!r||r.length===0||_r(r)}runScriptlets(r){if(!(!r||!r.length))for(const t of r){if(!t||typeof t.code!="string"||!t.code){Rt.error("Missing precompiled scriptlet source",t&&t.name);continue}_r([t.code])}}}var Me;(function(e){
e.InitContentScript="InitContentScript"})(Me||(Me={}));const Nr=new An("[wBlock Scripts]",z.Error);if(Pn(Nr),!m||!m.runtime||!m.runtime.sendMessage)return;let k=!1;const kn=/just a moment|verifying you are human|attention required|enable cookies/i,Ue=e=>kn.test(e||""),Be=()=>{k||(k=!0,console.info("[wBlock] Cloudflare challenge context detected \u2014 skipping content script."))},Dn=()=>{try{const e=window.location&&typeof window.location.hostname=="string"?window.location.hostname:"",r=window.location&&
typeof window.location.pathname=="string"?window.location.pathname:"";if(e==="challenges.cloudflare.com"||r.startsWith("/cdn-cgi/challenge-platform")||r.startsWith("/cdn-cgi/challenge"))return!0}catch{}return!1},Mn=()=>{if(k)return;if(Ue(document.title)){Be();return}const e=typeof document<"u"?document.documentElement:null;if(!e||typeof MutationObserver>"u"||!/^https?:$/i.test(window.location&&window.location.protocol||""))return;const r='script[src^="/cdn-cgi/challenge-platform"],script[src*="c\
hallenges.cloudflare.com"],#challenge-form,#challenge-stage,#challenge-runner',t=s=>s.nodeType===1&&(s.matches(r)||!!s.querySelector(r)||s.tagName==="TITLE"&&Ue(document.title));try{const s=new MutationObserver(i=>{if(k){s.disconnect();return}for(const l of i){const c=l.target.nodeName==="TITLE";for(const a of l.addedNodes)if(c&&Ue(document.title)||t(a)){n(),Be();return}}}),n=()=>{s.disconnect(),document.removeEventListener("DOMContentLoaded",o)},o=()=>{n(),!k&&(document.querySelector(r)||Ue(document.
title))&&Be()};s.observe(e,{childList:!0,subtree:!0}),document.addEventListener("DOMContentLoaded",o),setTimeout(()=>s.disconnect(),5e3)}catch{}};Dn()?Be():Mn();let Tt;const $r=[250,1e3,3e3],Un=e=>e&&e.state==="error"?Promise.resolve(!0):Promise.resolve(!(e&&typeof e.disabled=="boolean"&&typeof e.paused=="boolean")||e.disabled||e.paused);(async()=>{if(window.adguard={contentScript:new In},k)return;const e={type:Me.InitContentScript},t=(async()=>{for(let n=0;;n+=1){const o=await m.runtime.sendMessage(
e).catch(i=>({type:Me.InitContentScript,state:"error",error:String(i&&i.message?i.message:i)}));if(!(o&&o.state==="error")||n>=$r.length||k)return o;await new Promise(i=>setTimeout(i,$r[n]))}})();Tt=t.then(Un);const s=await t;if(!await Tt&&!k&&s!=null&&s.payload){const n=s.payload;window.adguard.contentScript.applyConfiguration(n)}})().catch(e=>{Nr.error("Error in content script: ",e)}),(async()=>{try{if(k||await(Tt||Promise.resolve(!1))||window.top!==window||!/^https?:/i.test(window.location.href)||
typeof m>"u"||!m.runtime||!m.runtime.sendMessage)return;const e=await m.runtime.sendMessage({action:"wblock:getCleanURL",url:window.location.href});let r=e&&typeof e.cleanUrl=="string"?e.cleanUrl:"";if(!r||r===window.location.href){const t=new URL(window.location.href);let s=!1;for(const n of Array.from(t.searchParams.keys()))/^(utm_|fbclid$|gclid$|dclid$|gbraid$|wbraid$|msclkid$|mc_cid$|mc_eid$|igshid$|yclid$|_hsenc$|_hsmi$|mkt_tok$|vero_id$|oly_anon_id$|oly_enc_id$)/i.test(n)&&(t.searchParams.
delete(n),s=!0);s&&(r=t.href)}if(r&&r!==window.location.href){if(k)return;console.info("[wBlock] Removing tracking parameters:",window.location.href,"\u2192",r),typeof history<"u"&&typeof history.replaceState=="function"&&history.replaceState(history.state,"",r)}}catch(e){try{const r=new URL(window.location.href);let t=!1;for(const s of Array.from(r.searchParams.keys()))/^(utm_|fbclid$|gclid$|dclid$|gbraid$|wbraid$|msclkid$|mc_cid$|mc_eid$|igshid$|yclid$|_hsenc$|_hsmi$|mkt_tok$|vero_id$|oly_anon_id$|oly_enc_id$)/i.
test(s)&&(r.searchParams.delete(s),t=!0);if(t&&r.href!==window.location.href){if(k)return;console.info("[wBlock] Removing common tracking parameters:",window.location.href,"\u2192",r.href),typeof history<"u"&&typeof history.replaceState=="function"&&history.replaceState(history.state,"",r.href)}}catch{console.warn("[wBlock] URL cleanup fallback failed:",e)}}})()})(typeof browser>"u"?void 0:browser);
